config/routes.rb
Rails.application.routes.draw do
  resources :chirps
  devise_for :users

  post "/follows" => "follows#create", as: :start_following
  post "/follows/stop" => "follows#destroy", as: :stop_following

  root 'chirps#index'

end

app/models/chirp.rb
class Chirp < ActiveRecord::Base
  paginates_per 8
  belongs_to :user

  def self.timeline(user)
   follower_ids = user.following_users.map(&:id)
   all_ids= follower_ids << user.id
   Chirp.where(user_id: all_ids).order("created_at DESC")
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 acts_as_follower
 acts_as_followable
 has_many :chirps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @timeline = Chirp.timeline(current_user).page params[:page]
  end

  def new
    @chirp = Chirp.new
  end

  def create
    @chirp = Chirp.new(chirp_params)

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to @chirp, notice: 'Chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'Chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    def chirp_params
      params.fetch(:chirp, {})
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
   before_action :authenticate_user!

  def create
    their_user_id = params[:user_id]
    me = current_user
    them = User.find(their_user_id)

    me.follow(them)

    redirect_to root_path
  end

  def destroy
    their_user_id = params[:user_id]
    me = current_user
    them = User.find(their_user_id)

    me.stop_following(them)

    redirect_to root_path

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/chirps/_form.html.haml
= simple_form_for(@chirp) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/chirps/edit.html.haml
%h1 Editing chirp

= render 'form'

= link_to 'Show', @chirp
\|
= link_to 'Back', chirps_path

app/views/chirps/index.html.haml
.row
  .col-md-3
    .ui-329
      .item
        .head.clearfix
          %img.img-responsive{:alt => "", :src => "img/ui-329/1.jpg"}/
          %h2
            %a{:href => "#"} Jhon Deo
            %span UI/UX Designer
        .content
          %ul.list-unstyled
            %li
              %a{:href => "#"}
                %i.fa.fa-phone.bg-red
                +39 - 384 - 493 - 3828
            %li
              %a{:href => "#"}
                %i.fa.fa-envelope.bg-green
                janedoe@gmail.com
            %li
              %a{:href => "#"}
                %i.fa.fa-twitter.bg-lblue
                @janedoe
            %li
              %a{:href => "#"}
                %i.fa.fa-facebook.bg-blue
                facebook.com/janedeo


  .col-md-6
    / UI 46 Starts
    .ui-246
      / Heading Starts
      .ui-heading
        .ui-image
          / Image
          %a{:href => "#"}
            %img.img-responsive{:alt => "#", :src => "img/ui-246/5.jpg"}/
          / Name
          %h4
            %a{:href => "#"}
              James Deo
              %span @james
        .ui-date
          / Date and Time
          11 Oct 2014
      .clearfix
      / Heading Ends
      / Content Starts
      .ui-content
        You asked, Font Awesome delivers with 58 shiny new icons in version 3.2. Want to request new icons? Here's how. Need vectors or want to use on the desktop?
      / Content Ends
      %hr/
      / Footer Starts
      .ui-footer.clearfix
        / Twitter Icons
        .twitter-icon
          %a.btn-twitter{:href => "#"}
            %i.fa.fa-twitter.lblue>
             Follow
        / Icons
        .icons
          %a{:href => "#"}
            %i.fa.fa-reply.icon-color
          %a{:href => "#"}
            %i.fa.fa-retweet.icon-color
          %a{:href => "#"}
            %i.fa.fa-star.icon-color
    .ui-89
      .ui-social
        .tab-content
          #facebook.tab-pane.active
            %textarea.form-control{:placeholder => "Chirp Chirp", :rows => "4"}
            %button.btn-sm.btn.btn-red{:type => "submit"} Submit
            %button.btn-sm.btn.btn-white{:type => "reset"} Reset
    = paginate @timeline

  .col-md-3
    .ui-x
      / Main Heading
      %h2
        %a{:href => "#"} Following
      - current_user.all_following.each do |user|
        %a.ui-item.clearfix{:href => "#"}
          %i.fa.fa-joomla
          %span.ui-details
            %span= user.email
            -# %span= link_to "Unfollow", stop_following_path(user_id: user.id), method: :post

%ul.list-unstyled
  - @users.reject{|u| u.id == current_user.id}.sample(5).each do |user|
    - unless current_user.following?(user)
      %li
        = user.email
        = link_to "Follow", start_following_path(user_id: user.id), method: :post, class: "btn btn-default btn-xs"

app/views/chirps/new.html.haml
%h1 New chirp

= render 'form'

= link_to 'Back', chirps_path

app/views/chirps/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_chirp_path(@chirp)
\|
= link_to 'Back', chirps_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chirpster
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
  - if current_user.nil?
    %ul.nav.navbar-nav.navbar-left
      %li
        %a
          Welcome,
          %b Guest
    %ul.nav.navbar-nav.navbar-right
      %li= link_to "Signup", new_user_registration_path
  - else
    %ul.nav.navbar-nav.navbar-left
      %li
        %a
          Welcome,
          -# %b= @current_user.firstname.capitalize
    %ul.nav.navbar-nav.navbar-right
      %li= link_to "Logout", destroy_user_session_path, method: :delete

  .container
    = yield